LOCAL_PATH := $(call my-dir)


include $(CLEAR_VARS)

LOCAL_MODULE:= ymImage
LOCAL_CPPFLAGS += -fexceptions
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../ymImage/include
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -llog

LOCAL_SRC_FILES :=\
ymImage/DataUtil.cpp \
ymImage/ymImage.cpp \
ymImage/ImageHandlerJNI.cpp \
ymImage/include/CxImage/tif_xfile.cpp \
ymImage/include/CxImage/ximabmp.cpp \
ymImage/include/CxImage/ximadsp.cpp \
ymImage/include/CxImage/ximaenc.cpp \
ymImage/include/CxImage/ximaexif.cpp \
ymImage/include/CxImage/ximage.cpp \
ymImage/include/CxImage/ximagif.cpp \
ymImage/include/CxImage/ximahist.cpp \
ymImage/include/CxImage/ximaico.cpp \
ymImage/include/CxImage/ximainfo.cpp \
ymImage/include/CxImage/ximaint.cpp \
ymImage/include/CxImage/ximajas.cpp \
ymImage/include/CxImage/ximajbg.cpp \
ymImage/include/CxImage/ximajpg.cpp \
ymImage/include/CxImage/ximalpha.cpp \
ymImage/include/CxImage/ximalyr.cpp \
ymImage/include/CxImage/ximamng.cpp \
ymImage/include/CxImage/ximapal.cpp \
ymImage/include/CxImage/ximapcx.cpp \
ymImage/include/CxImage/ximapng.cpp \
ymImage/include/CxImage/ximaraw.cpp \
ymImage/include/CxImage/ximasel.cpp \
ymImage/include/CxImage/ximaska.cpp \
ymImage/include/CxImage/ximatga.cpp \
ymImage/include/CxImage/ximath.cpp \
ymImage/include/CxImage/ximatif.cpp \
ymImage/include/CxImage/ximatran.cpp \
ymImage/include/CxImage/ximawbmp.cpp \
ymImage/include/CxImage/ximawmf.cpp \
ymImage/include/CxImage/ximawnd.cpp \
ymImage/include/CxImage/xmemfile.cpp \
ymImage/include/jasper/jas_cm.c \
ymImage/include/jasper/jas_debug.c \
ymImage/include/jasper/jas_getopt.c \
ymImage/include/jasper/jas_icc.c \
ymImage/include/jasper/jas_iccdata.c \
ymImage/include/jasper/jas_image.c \
ymImage/include/jasper/jas_init.c \
ymImage/include/jasper/jas_malloc.c \
ymImage/include/jasper/jas_seq.c \
ymImage/include/jasper/jas_stream.c \
ymImage/include/jasper/jas_string.c \
ymImage/include/jasper/jas_tmr.c \
ymImage/include/jasper/jas_tvp.c \
ymImage/include/jasper/jas_version.c \
ymImage/include/jasper/bmp_cod.c \
ymImage/include/jasper/bmp_dec.c \
ymImage/include/jasper/bmp_enc.c \
ymImage/include/jasper/jp2_cod.c \
ymImage/include/jasper/jp2_dec.c \
ymImage/include/jasper/jp2_enc.c \
ymImage/include/jasper/jpc_bs.c \
ymImage/include/jasper/jpc_cs.c \
ymImage/include/jasper/jpc_dec.c \
ymImage/include/jasper/jpc_enc.c \
ymImage/include/jasper/jpc_math.c \
ymImage/include/jasper/jpc_mct.c \
ymImage/include/jasper/jpc_mqcod.c \
ymImage/include/jasper/jpc_mqdec.c \
ymImage/include/jasper/jpc_mqenc.c \
ymImage/include/jasper/jpc_qmfb.c \
ymImage/include/jasper/jpc_t1cod.c \
ymImage/include/jasper/jpc_t1dec.c \
ymImage/include/jasper/jpc_t1enc.c \
ymImage/include/jasper/jpc_t2cod.c \
ymImage/include/jasper/jpc_t2dec.c \
ymImage/include/jasper/jpc_t2enc.c \
ymImage/include/jasper/jpc_tagtree.c \
ymImage/include/jasper/jpc_tsfb.c \
ymImage/include/jasper/jpc_util.c \
ymImage/include/jasper/jpg_dec.c \
ymImage/include/jasper/jpg_enc.c \
ymImage/include/jasper/jpg_val.c \
ymImage/include/jasper/mif_cod.c \
ymImage/include/jasper/pgx_cod.c \
ymImage/include/jasper/pgx_dec.c \
ymImage/include/jasper/pgx_enc.c \
ymImage/include/jasper/pnm_cod.c \
ymImage/include/jasper/pnm_dec.c \
ymImage/include/jasper/pnm_enc.c \
ymImage/include/jasper/ras_cod.c \
ymImage/include/jasper/ras_dec.c \
ymImage/include/jasper/ras_enc.c \
ymImage/include/jpeg/jcapimin.c \
ymImage/include/jpeg/jcapistd.c \
ymImage/include/jpeg/jccoefct.c \
ymImage/include/jpeg/jccolor.c \
ymImage/include/jpeg/jcdctmgr.c \
ymImage/include/jpeg/jchuff.c \
ymImage/include/jpeg/jcinit.c \
ymImage/include/jpeg/jcmainct.c \
ymImage/include/jpeg/jcmarker.c \
ymImage/include/jpeg/jcmaster.c \
ymImage/include/jpeg/jcomapi.c \
ymImage/include/jpeg/jcparam.c \
ymImage/include/jpeg/jcphuff.c \
ymImage/include/jpeg/jcprepct.c \
ymImage/include/jpeg/jcsample.c \
ymImage/include/jpeg/jctrans.c \
ymImage/include/jpeg/jdapimin.c \
ymImage/include/jpeg/jdapistd.c \
ymImage/include/jpeg/jdatadst.c \
ymImage/include/jpeg/jdatasrc.c \
ymImage/include/jpeg/jdcoefct.c \
ymImage/include/jpeg/jdcolor.c \
ymImage/include/jpeg/jddctmgr.c \
ymImage/include/jpeg/jdhuff.c \
ymImage/include/jpeg/jdinput.c \
ymImage/include/jpeg/jdmainct.c \
ymImage/include/jpeg/jdmarker.c \
ymImage/include/jpeg/jdmaster.c \
ymImage/include/jpeg/jdmerge.c \
ymImage/include/jpeg/jdphuff.c \
ymImage/include/jpeg/jdpostct.c \
ymImage/include/jpeg/jdsample.c \
ymImage/include/jpeg/jdtrans.c \
ymImage/include/jpeg/jerror.c \
ymImage/include/jpeg/jfdctflt.c \
ymImage/include/jpeg/jfdctfst.c \
ymImage/include/jpeg/jfdctint.c \
ymImage/include/jpeg/jidctflt.c \
ymImage/include/jpeg/jidctfst.c \
ymImage/include/jpeg/jidctint.c \
ymImage/include/jpeg/jidctred.c \
ymImage/include/jpeg/jmemmgr.c \
ymImage/include/jpeg/jmemnobs.c \
ymImage/include/jpeg/jquant1.c \
ymImage/include/jpeg/jquant2.c \
ymImage/include/jpeg/jutils.c \
ymImage/include/png/png.c \
ymImage/include/png/pngerror.c \
ymImage/include/png/pnggccrd.c \
ymImage/include/png/pngget.c \
ymImage/include/png/pngmem.c \
ymImage/include/png/pngpread.c \
ymImage/include/png/pngread.c \
ymImage/include/png/pngrio.c \
ymImage/include/png/pngrtran.c \
ymImage/include/png/pngrutil.c \
ymImage/include/png/pngset.c \
ymImage/include/png/pngtrans.c \
ymImage/include/png/pngvcrd.c \
ymImage/include/png/pngwio.c \
ymImage/include/png/pngwrite.c \
ymImage/include/png/pngwtran.c \
ymImage/include/png/pngwutil.c \
ymImage/include/tiff/fax3sm_winnt.c \
ymImage/include/tiff/tif_aux.c \
ymImage/include/tiff/tif_close.c \
ymImage/include/tiff/tif_codec.c \
ymImage/include/tiff/tif_compress.c \
ymImage/include/tiff/tif_dir.c \
ymImage/include/tiff/tif_dirinfo.c \
ymImage/include/tiff/tif_dirread.c \
ymImage/include/tiff/tif_dirwrite.c \
ymImage/include/tiff/tif_dumpmode.c \
ymImage/include/tiff/tif_error.c \
ymImage/include/tiff/tif_fax3.c \
ymImage/include/tiff/tif_flush.c \
ymImage/include/tiff/tif_getimage.c \
ymImage/include/tiff/tif_jpeg.c \
ymImage/include/tiff/tif_luv.c \
ymImage/include/tiff/tif_lzw.c \
ymImage/include/tiff/tif_next.c \
ymImage/include/tiff/tif_ojpeg.c \
ymImage/include/tiff/tif_open.c \
ymImage/include/tiff/tif_packbits.c \
ymImage/include/tiff/tif_pixarlog.c \
ymImage/include/tiff/tif_predict.c \
ymImage/include/tiff/tif_print.c \
ymImage/include/tiff/tif_read.c \
ymImage/include/tiff/tif_strip.c \
ymImage/include/tiff/tif_swab.c \
ymImage/include/tiff/tif_thunder.c \
ymImage/include/tiff/tif_tile.c \
ymImage/include/tiff/tif_version.c \
ymImage/include/tiff/tif_warning.c \
ymImage/include/tiff/tif_write.c \
ymImage/include/tiff/tif_zip.c \
ymImage/include/zlib/adler32.c \
ymImage/include/zlib/compress.c \
ymImage/include/zlib/crc32.c \
ymImage/include/zlib/deflate.c \
ymImage/include/zlib/gzio.c \
ymImage/include/zlib/infback.c \
ymImage/include/zlib/inffast.c \
ymImage/include/zlib/inflate.c \
ymImage/include/zlib/inftrees.c \
ymImage/include/zlib/trees.c \
ymImage/include/zlib/uncompr.c \
ymImage/include/zlib/zutil.c \

include $(BUILD_SHARED_LIBRARY)





include $(CLEAR_VARS)

LOCAL_MODULE:= libspeex
LOCAL_CFLAGS = -DFIXED_POINT -DUSE_KISS_FFT -DEXPORT="" -UHAVE_CONFIG_H
LOCAL_C_INCLUDES := $(LOCAL_PATH)/speex/include

LOCAL_SRC_FILES :=\
speex/libspeex/bits.c \
speex/libspeex/buffer.c \
speex/libspeex/cb_search.c \
speex/libspeex/exc_10_16_table.c \
speex/libspeex/exc_10_32_table.c \
speex/libspeex/exc_20_32_table.c \
speex/libspeex/exc_5_256_table.c \
speex/libspeex/exc_5_64_table.c \
speex/libspeex/exc_8_128_table.c \
speex/libspeex/fftwrap.c \
speex/libspeex/filterbank.c \
speex/libspeex/filters.c \
speex/libspeex/gain_table.c \
speex/libspeex/gain_table_lbr.c \
speex/libspeex/hexc_10_32_table.c \
speex/libspeex/hexc_table.c \
speex/libspeex/high_lsp_tables.c \
speex/libspeex/jitter.c \
speex/libspeex/kiss_fft.c \
speex/libspeex/kiss_fftr.c \
speex/libspeex/lpc.c \
speex/libspeex/lsp.c \
speex/libspeex/lsp_tables_nb.c \
speex/libspeex/ltp.c \
speex/libspeex/mdf.c \
speex/libspeex/modes.c \
speex/libspeex/modes_wb.c \
speex/libspeex/nb_celp.c \
speex/libspeex/preprocess.c \
speex/libspeex/quant_lsp.c \
speex/libspeex/resample.c \
speex/libspeex/sb_celp.c \
speex/libspeex/scal.c \
speex/libspeex/smallft.c \
speex/libspeex/speex.c \
speex/libspeex/speex_callbacks.c \
speex/libspeex/speex_header.c \
speex/libspeex/stereo.c \
speex/libspeex/vbr.c \
speex/libspeex/vq.c \
speex/libspeex/window.c \
speex/speex_jni.cpp \

include $(BUILD_SHARED_LIBRARY)
